# Generated by Django 5.2 on 2026-06-19 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendancePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_start_time', models.TimeField(default='09:30')),
                ('grace_period_minutes', models.PositiveSmallIntegerField(default=5)),
                ('office_end_time', models.TimeField(default='18:30')),
                ('half_day_hours', models.DecimalField(decimal_places=2, default=4, max_digits=4)),
                ('full_day_hours', models.DecimalField(decimal_places=2, default=8, max_digits=4)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Attendance policy',
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField()),
                ('check_in_time', models.TimeField(blank=True, null=True)),
                ('check_out_time', models.TimeField(blank=True, null=True)),
                ('check_in_status', models.CharField(blank=True, choices=[('On Time', 'On Time'), ('Grace Period', 'Grace Period'), ('Late', 'Late')], max_length=20)),
                ('attendance_status', models.CharField(choices=[('Present', 'Present'), ('Present (Late)', 'Present (Late)'), ('Present (Early Exit)', 'Present (Early Exit)'), ('Present (Late + Early Exit)', 'Present (Late + Early Exit)'), ('Absent', 'Absent'), ('Half Day', 'Half Day'), ('Leave', 'Leave')], default='Absent', max_length=40)),
                ('is_late', models.BooleanField(default=False)),
                ('late_minutes', models.PositiveIntegerField(default=0)),
                ('is_early_exit', models.BooleanField(default=False)),
                ('early_exit_minutes', models.PositiveIntegerField(default=0)),
                ('working_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('source', models.CharField(choices=[('Manual', 'Manual'), ('QR', 'QR'), ('QR + Location', 'QR + Location'), ('Admin', 'Admin')], default='Manual', max_length=20)),
                ('qr_reference', models.CharField(blank=True, max_length=120)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location_verified', models.BooleanField(default=False)),
                ('notes', models.CharField(blank=True, max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='portal.employee')),
            ],
            options={
                'ordering': ['-attendance_date', 'employee__name'],
                'constraints': [models.UniqueConstraint(fields=('employee', 'attendance_date'), name='unique_employee_attendance_date')],
            },
        ),
    ]
