# Generated by Django 5.2 on 2026-06-22 16:25

from django.db import migrations, models

def migrate_bde_to_bdo(apps, schema_editor):
    UserRole = apps.get_model("portal", "UserRole")
    UserRole.objects.filter(role="BDE").update(role="BDO")

def migrate_bdo_to_bde(apps, schema_editor):
    UserRole = apps.get_model("portal", "UserRole")
    UserRole.objects.filter(role="BDO").update(role="BDE")


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_userrole'),
    ]

    operations = [
        migrations.RunPython(migrate_bde_to_bdo, migrate_bdo_to_bde),
        migrations.AlterField(
            model_name='userrole',
            name='role',
            field=models.CharField(choices=[('HR', 'HR'), ('ADMIN', 'Admin'), ('ACCOUNTANT', 'Accountant'), ('BDO', 'BDO'), ('EMPLOYEE', 'Employee')], max_length=20),
        ),
    ]
