# Generated by Django 5.2 on 2026-07-24 05:05

from django.db import migrations, models


CANONICAL_DEPARTMENTS = [
    ('Web Development', 'Web Development'),
    ('Video Editing', 'Video Editing'),
    ('Design', 'Design'),
    ('Digital Marketing', 'Digital Marketing'),
    ('Accountant', 'Accountant'),
    ('HR', 'HR'),
    ('Operations', 'Operations'),
]


def forwards_department_names(apps, schema_editor):
    Employee = apps.get_model('portal', 'Employee')
    Meeting = apps.get_model('portal', 'Meeting')
    mapping = {
        'Engineering': 'Web Development',
        'Web Developer': 'Web Development',
        'Designer': 'Design',
        'Finance': 'Accountant',
        'Sales': 'Digital Marketing',
        'Operation Head': 'Operations',
    }
    for old, new in mapping.items():
        Employee.objects.filter(department=old).update(department=new)
        Meeting.objects.filter(department=old).update(department=new)


def backwards_department_names(apps, schema_editor):
    Employee = apps.get_model('portal', 'Employee')
    Meeting = apps.get_model('portal', 'Meeting')
    mapping = {
        'Web Development': 'Engineering',
        'Accountant': 'Finance',
        'Digital Marketing': 'Sales',
    }
    for old, new in mapping.items():
        Employee.objects.filter(department=old).update(department=new)
        Meeting.objects.filter(department=old).update(department=new)


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_userrole_bde'),
    ]

    operations = [
        migrations.RunPython(forwards_department_names, backwards_department_names),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(choices=CANONICAL_DEPARTMENTS, max_length=50),
        ),
    ]
