# Generated by Django 5.2 on 2026-07-28 06:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_client_employee_team_lead_alter_userrole_role_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['attendance_date'], name='attendance_date_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['attendance_status'], name='attendance_status_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['status', 'name'], name='employee_status_name_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['department', 'status'], name='employee_dept_status_idx'),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['status', 'created_at'], name='leave_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['date', 'time'], name='meeting_date_time_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['department', 'date', 'time'], name='meeting_dept_date_time_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read', 'created_at'], name='notif_user_read_created_idx'),
        ),
        migrations.AddIndex(
            model_name='workassignment',
            index=models.Index(fields=['due_date', 'status'], name='work_due_status_idx'),
        ),
        migrations.AddIndex(
            model_name='workassignment',
            index=models.Index(fields=['status', 'priority'], name='work_status_priority_idx'),
        ),
    ]
