# Generated by Django 5.2 on 2026-07-28 09:07

from django.conf import settings
from django.db import migrations, models


def backfill_quantity_fields(apps, schema_editor):
    WorkAssignment = apps.get_model('portal', 'WorkAssignment')
    WorkAssignment.objects.update(
        assigned_quantity=100,
        completed_quantity=models.F('progress'),
        unit='%',
    )
    WorkAssignment.objects.filter(status='Completed').update(completed_at=models.F('updated_at'))


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_attendancerecord_attendance_date_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workassignment',
            name='assigned_quantity',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='workassignment',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workassignment',
            name='completed_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workassignment',
            name='unit',
            field=models.CharField(default='%', max_length=30),
        ),
        migrations.RunPython(backfill_quantity_fields, noop_reverse),
        migrations.AddConstraint(
            model_name='workassignment',
            constraint=models.CheckConstraint(condition=models.Q(('assigned_quantity__gt', 0)), name='work_assigned_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='workassignment',
            constraint=models.CheckConstraint(condition=models.Q(('completed_quantity__gte', 0)), name='work_completed_quantity_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='workassignment',
            constraint=models.CheckConstraint(condition=models.Q(('completed_quantity__lte', models.F('assigned_quantity'))), name='work_completed_quantity_lte_assigned'),
        ),
    ]
