# Generated by Django 5.2 on 2026-07-28 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_workassignment_assigned_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkDeliverable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('brief', models.TextField(blank=True)),
                ('work_type', models.CharField(max_length=80)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Blocked', 'Blocked'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to='portal.workassignment')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_deliverables', to='portal.client')),
            ],
            options={
                'ordering': ['due_date', 'client__name', 'title'],
                'indexes': [models.Index(fields=['assignment', 'status'], name='deliver_assignment_status_idx'), models.Index(fields=['client', 'due_date'], name='deliver_client_due_idx'), models.Index(fields=['status', 'due_date'], name='deliver_status_due_idx')],
            },
        ),
    ]
