# Generated by Django 5.2 on 2026-08-04 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0013_clientworksharelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='workassignment',
            name='reviewer_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
