# Generated by Django 5.2 on 2026-08-04 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_reviewer_names_to_fk(apps, schema_editor):
    WorkAssignment = apps.get_model('portal', 'WorkAssignment')
    User = apps.get_model('auth', 'User')
    Employee = apps.get_model('portal', 'Employee')

    for assignment in WorkAssignment.objects.all():
        if assignment.reviewer_id:
            continue
        rev_name = (assignment.reviewer_name or "").strip()
        if not rev_name:
            if assignment.assigned_by_id:
                assignment.reviewer_id = assignment.assigned_by_id
                assignment.save(update_fields=['reviewer'])
            continue

        emp = Employee.objects.filter(name__iexact=rev_name).select_related('user').first()
        if emp and emp.user_id:
            assignment.reviewer_id = emp.user_id
            assignment.save(update_fields=['reviewer'])
            continue

        user_match = User.objects.filter(username__iexact=rev_name).first()
        if not user_match:
            user_match = User.objects.filter(first_name__iexact=rev_name).first()
        if user_match:
            assignment.reviewer_id = user_match.id
            assignment.save(update_fields=['reviewer'])
            continue

        if assignment.assigned_by_id:
            assignment.reviewer_id = assignment.assigned_by_id
            assignment.save(update_fields=['reviewer'])


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0014_workassignment_reviewer_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workassignment',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_work_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workassignment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Ongoing', 'Ongoing'), ('Blocked', 'Blocked'), ('In Review', 'In Review'), ('Changes Requested', 'Changes Requested'), ('Rejected', 'Rejected'), ('Approved', 'Approved'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='workdeliverable',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Ongoing', 'Ongoing'), ('Blocked', 'Blocked'), ('In Review', 'In Review'), ('Changes Requested', 'Changes Requested'), ('Rejected', 'Rejected'), ('Approved', 'Approved'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
        migrations.RunPython(migrate_reviewer_names_to_fk, reverse_code=migrations.RunPython.noop),
    ]
