# Generated by Django 5.2 on 2026-08-05 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0016_alter_attendancecorrection_employee_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='attendancerecord',
            name='unique_employee_attendance_date',
        ),
        migrations.RemoveConstraint(
            model_name='employeekpirating',
            name='unique_employee_kpi_rating_month',
        ),
        migrations.RemoveConstraint(
            model_name='salaryslip',
            name='unique_employee_salary_month',
        ),
    ]
