# Generated by Django 5.2 on 2026-08-05 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0017_remove_attendancerecord_unique_employee_attendance_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='role',
            field=models.CharField(choices=[('HR', 'HR'), ('ADMIN', 'Admin'), ('ACCOUNTANT', 'Accountant'), ('BDE', 'BDE'), ('TEAM_LEAD', 'Team Lead'), ('EMPLOYEE', 'Employee'), ('OPERATIONS', 'Operations'), ('OPERATIONS_HEAD', 'Operations Head')], max_length=20),
        ),
        migrations.AlterField(
            model_name='workassignment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Ongoing', 'Ongoing'), ('Blocked', 'Blocked'), ('In Review', 'In Review'), ('Changes Requested', 'Changes Requested'), ('Rejected', 'Rejected'), ('Approved', 'Approved'), ('Completed', 'Completed'), ('Published', 'Published')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='workdeliverable',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Ongoing', 'Ongoing'), ('Blocked', 'Blocked'), ('In Review', 'In Review'), ('Changes Requested', 'Changes Requested'), ('Rejected', 'Rejected'), ('Approved', 'Approved'), ('Completed', 'Completed'), ('Published', 'Published')], default='Pending', max_length=20),
        ),
    ]
