# Generated by Django 5.2 on 2026-08-10 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0018_alter_userrole_role_alter_workassignment_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_superadmin_wildcard', models.BooleanField(default=False)),
                ('is_system_role', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PortalPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('route_path', models.CharField(max_length=200, unique=True)),
                ('module_code', models.CharField(max_length=50, unique=True)),
                ('icon', models.CharField(default='LayoutDashboard', max_length=50)),
                ('sidebar_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sidebar_order', 'title'],
            },
        ),
        migrations.AlterField(
            model_name='userrole',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('HR', 'HR'), ('ADMIN', 'Admin'), ('ACCOUNTANT', 'Accountant'), ('BDE', 'BDE'), ('TEAM_LEAD', 'Team Lead'), ('EMPLOYEE', 'Employee'), ('OPERATIONS', 'Operations'), ('OPERATIONS_HEAD', 'Operations Head')], max_length=20),
        ),
        migrations.AddField(
            model_name='userrole',
            name='dynamic_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_roles', to='portal.dynamicrole'),
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view', models.BooleanField(default=False)),
                ('can_create', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='portal.portalpage')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='portal.dynamicrole')),
            ],
            options={
                'ordering': ['page__sidebar_order', 'page__title'],
                'unique_together': {('role', 'page')},
            },
        ),
    ]
