# Generated by Django 5.2 on 2026-08-13 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0022_seed_departments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workassignment',
            name='status',
            field=models.CharField(choices=[('Assigned', 'Assigned'), ('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Ongoing', 'Ongoing'), ('Blocked', 'Blocked'), ('In Review', 'In Review'), ('Changes Requested', 'Changes Requested'), ('Rejected', 'Rejected'), ('Approved', 'Approved'), ('Completed', 'Completed'), ('Published', 'Published')], default='Assigned', max_length=20),
        ),
        migrations.AlterField(
            model_name='workdeliverable',
            name='status',
            field=models.CharField(choices=[('Assigned', 'Assigned'), ('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Ongoing', 'Ongoing'), ('Blocked', 'Blocked'), ('In Review', 'In Review'), ('Changes Requested', 'Changes Requested'), ('Rejected', 'Rejected'), ('Approved', 'Approved'), ('Completed', 'Completed'), ('Published', 'Published')], default='Assigned', max_length=20),
        ),
    ]
