# Generated by Django 5.2 on 2026-08-19 05:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0023_alter_workassignment_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workassignment',
            name='review_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='workassignment',
            name='review_status',
            field=models.CharField(choices=[('PENDING_REVIEW', 'Pending Review'), ('OK', 'OK'), ('CORRECTION_NEEDED', 'Correction Needed')], default='PENDING_REVIEW', max_length=30),
        ),
        migrations.AddField(
            model_name='workassignment',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workassignment',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_reviewed_work', to=settings.AUTH_USER_MODEL),
        ),
    ]
