# Generated by Django 5.2 on 2026-08-22 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0024_workassignment_review_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancepolicy',
            name='early_checkout_half_day_cutoff',
            field=models.TimeField(default='18:00'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='check_in_distance_meters',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='check_out_distance_meters',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='check_out_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='check_out_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='attendance_photos/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='attendancepolicy',
            name='allowed_radius_meters',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='attendancepolicy',
            name='office_latitude',
            field=models.DecimalField(decimal_places=6, default='8.521310', max_digits=9),
        ),
        migrations.AlterField(
            model_name='attendancepolicy',
            name='office_longitude',
            field=models.DecimalField(decimal_places=6, default='76.978630', max_digits=9),
        ),
        migrations.AlterField(
            model_name='workassignment',
            name='status',
            field=models.CharField(choices=[('Backlog', 'Backlog'), ('Assigned', 'Assigned'), ('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Ongoing', 'Ongoing'), ('Blocked', 'Blocked'), ('In Review', 'In Review'), ('Changes Requested', 'Changes Requested'), ('Rejected', 'Rejected'), ('Approved', 'Approved'), ('Completed', 'Completed'), ('Published', 'Published')], default='Assigned', max_length=20),
        ),
        migrations.AlterField(
            model_name='workdeliverable',
            name='status',
            field=models.CharField(choices=[('Backlog', 'Backlog'), ('Assigned', 'Assigned'), ('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Ongoing', 'Ongoing'), ('Blocked', 'Blocked'), ('In Review', 'In Review'), ('Changes Requested', 'Changes Requested'), ('Rejected', 'Rejected'), ('Approved', 'Approved'), ('Completed', 'Completed'), ('Published', 'Published')], default='Assigned', max_length=20),
        ),
    ]
