from .serializer_modules.announcements import AnnouncementSerializer
from .serializer_modules.attendance import AttendanceCorrectionSerializer, AttendancePolicySerializer, AttendanceRecordSerializer
from .serializer_modules.audit_logs import AuditLogSerializer
from .serializer_modules.auth import ProfileSerializer, RegisterSerializer
from .serializer_modules.employees import EmployeeSerializer
from .serializer_modules.leaves import LeaveSerializer
from .serializer_modules.meetings import MeetingSerializer
from .serializer_modules.notifications import NotificationSerializer
from .serializer_modules.salary import SalarySlipSerializer
from .serializer_modules.work import ClientSerializer, WorkAssignmentSerializer
