import { DepartmentMeta } from "../types";

export const departmentsConfig: DepartmentMeta[] = [
  {
    id: "accounting",
    name: "Accounting & Finance",
    shortName: "Accounting",
    description: "Tax, GST, invoice numbers to words, ledgers, margin calculations & payment terms.",
    iconName: "Calculator",
    accentColor: "#059669",
    badgeBg: "rgba(5, 150, 105, 0.12)",
  },
  {
    id: "marketing",
    name: "Digital Marketing",
    shortName: "Marketing",
    description: "Campaign UTMs, SEO meta tags, character limits, slugs & campaign utilities.",
    iconName: "Megaphone",
    accentColor: "#D97706",
    badgeBg: "rgba(217, 119, 6, 0.12)",
  },
  {
    id: "design",
    name: "Photo & Design",
    shortName: "Photo & Design",
    description: "Client-side image compression, format conversion, resizer, color codes & picker.",
    iconName: "Palette",
    accentColor: "#8B5CF6",
    badgeBg: "rgba(139, 92, 246, 0.12)",
  },
  {
    id: "video",
    name: "Video Production",
    shortName: "Video",
    description: "Aspect ratios, frame rates, timecodes, resolution presets for social platforms.",
    iconName: "Video",
    accentColor: "#EC4899",
    badgeBg: "rgba(236, 72, 153, 0.12)",
  },
  {
    id: "development",
    name: "Web Development",
    shortName: "Engineering",
    description: "JSON format & validation, Base64, URL encoding, regex testing, JWTs & hashes.",
    iconName: "Code2",
    accentColor: "#2563EB",
    badgeBg: "rgba(37, 99, 235, 0.12)",
  },
  {
    id: "operations",
    name: "Operations & HR",
    shortName: "Operations",
    description: "CSV data viewer, text cleanup, timestamps, file sizes, working day calculators.",
    iconName: "Layers",
    accentColor: "#0284C7",
    badgeBg: "rgba(2, 132, 199, 0.12)",
  },
  {
    id: "business",
    name: "Business & Sales",
    shortName: "Business",
    description: "Discounts, commission splits, profit margins, sales percentage breakdowns.",
    iconName: "TrendingUp",
    accentColor: "#10B981",
    badgeBg: "rgba(16, 185, 129, 0.12)",
  },
  {
    id: "general",
    name: "General Utilities",
    shortName: "General",
    description: "QR codes, secure passwords, UUIDs, unit converters, universal productivity tools.",
    iconName: "Sparkles",
    accentColor: "#6366F1",
    badgeBg: "rgba(99, 102, 241, 0.12)",
  },
];
